language: swift
osx_image: xcode15.3
branches:
  only:
    - main

before_install:
  -gem install fastlane --no-ri --no-rdoc --no-document
install: true
script:
  -fastlane scan --scheme TAU --device "iPhone XR"
